services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: recetario
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10

  backend:
    image: ghcr.io/marcosbugliotti/recetario-backend:v0.1.0
    environment:
      DATABASE_URL: "postgresql://postgres:${DB_PASSWORD}@db:5432/recetario"
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: ghcr.io/marcosbugliotti/recetario-frontend:v0.1.0
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
